<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAt8STJm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAt8STJm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAt8STJm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAt8STJm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAt8STJm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'At8STJm',
    'container.build_id' => 'ae83fe3c',
    'container.build_time' => 1651022874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAt8STJm');
